version: "3.7"
services:
  go-web:
    build:
      context: ./   
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/docker-go
    ports:  
      - "8080:8080"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    command: ["./app"]